---
name: ✍️ Check Commit Signatures
description: Check if all commits in a pull request are signed with a verified signature.

runs:
  using: composite
  steps:
    - name: Check for unverified commits
      id: check_unverified_commits
      uses: actions/github-script@v7
      with:
        script: |
          const prNumber = context.payload.pull_request.number;
          const { data: commits } = await github.rest.pulls.listCommits({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber,
          });

          const unverified = commits.filter(commit => !commit.commit.verification.verified);

          if (unverified.length > 0) {
            const message = `⚠️ This PR contains ${unverified.length} commit(s) without verified signatures. Please sign your commits. More information on this is available [here](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: message,
            });
          }
