---
name: Set Up Container Structure Test
description: This action installs Google's [Container Structure Test](https://github.com/GoogleContainerTools/container-structure-test)

inputs:
  github_token:
    description: GitHub token for authentication
    required: false
    default: ${{ github.token }}
  version:
    description: Version of Container Structure Test to install
    required: false
    default: "latest"

outputs: {}

runs:
  using: composite
  steps:
    - name: Install Container Structure Test
      id: install_container_structure_test
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        VERSION: ${{ inputs.version }}
      run: | # zizmor: ignore[github-env] we need to the binary to the path
        if [[ "$(uname --machine)" == "x86_64" ]]; then
          export architecture="amd64"
        elif [[ "$(uname --machine)" == "aarch64" ]]; then
          export architecture="arm64"
        else
          echo "Unsupported architecture: $(uname --machine)"
          exit 1
        fi

        if [[ "${VERSION}" == "latest" ]]; then
          export version="$(gh release list --repo GoogleContainerTools/container-structure-test --exclude-drafts --exclude-pre-releases --json "isLatest,tagName" | jq -r '.[] | select(.isLatest == true) | .tagName')"
        else
          export version="${VERSION}"
        fi

        mkdir --parents "${GITHUB_WORKSPACE}/.container-structure-test"

        curl --fail-with-body --location --silent "https://github.com/GoogleContainerTools/container-structure-test/releases/download/${version}/container-structure-test-linux-${architecture}" \
          --output "${GITHUB_WORKSPACE}/.container-structure-test/container-structure-test"

        gh release download \
          --repo GoogleContainerTools/container-structure-test \
          "${version}" \
          --pattern "container-structure-test-linux-${architecture}" \
          --output "${GITHUB_WORKSPACE}/.container-structure-test/container-structure-test" \
          --clobber

        chmod +x "${GITHUB_WORKSPACE}/.container-structure-test/container-structure-test"

        echo "${GITHUB_WORKSPACE}/.container-structure-test" >>"${GITHUB_PATH}"
