---
name: Set Up Container Structure Test
description: This action installs Google's [Container Structure Test](https://github.com/GoogleContainerTools/container-structure-test)

inputs:
  version:
    description: Version of Container Structure Test to install
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: | # zizmor: ignore[github-env] we need to the binary to the path
        if [[ "$(uname --machine)" == "x86_64" ]]; then
          export architecture="amd64"
        elif [[ "$(uname --machine)" == "aarch64" ]]; then
          export architecture="arm64"
        else
          echo "Unsupported architecture: $(uname --machine)"
          exit 1
        fi

        if [[ "${VERSION}" == "latest" ]]; then
          export version="$(curl --silent https://api.github.com/repos/GoogleContainerTools/container-structure-test/releases/latest | jq -r '.tag_name')"
        else
          export version="${VERSION}"
        fi

        mkdir --parents "${GITHUB_WORKSPACE}/.container-structure-test"

        curl --fail-with-body --location --silent "https://github.com/GoogleContainerTools/container-structure-test/releases/download/${version}/container-structure-test-linux-${architecture}" \
          --output "${GITHUB_WORKSPACE}/.container-structure-test/container-structure-test"

        chmod +x "${GITHUB_WORKSPACE}/.container-structure-test/container-structure-test"

        echo "${GITHUB_WORKSPACE}/.container-structure-test" >>"${GITHUB_PATH}"
