---
name: 🧪 Test setup-container-structure-test

on:
  pull_request:
    branches:
      - main
    paths:
      - setup-container-structure-test/**

permissions: {}

jobs:
  default:
    name: Default
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Run setup-container-structure-test
        id: setup_container_structure_test
        uses: ./setup-container-structure-test

      - name: Test container-structure-test command
        id: test_container_structure_test_command
        run: |
          container-structure-test version

  specify-version:
    name: Specify Version
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Run setup-container-structure-test
        id: setup_container_structure_test
        uses: ./setup-container-structure-test
        with:
          version: v1.19.3

      - name: Test container-structure-test command
        id: test_container_structure_test_command
        run: |
          container-structure-test version
