---
name: 🧪 Test clean-actions-runner

on:
  pull_request:
    branches:
      - main
    paths:
      - clean-actions-runner/**

permissions: {}

jobs:
  default:
    name: Default
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Run clean-actions-runner
        id: clean_actions_runner
        uses: ./clean-actions-runner
        with:
          confirm: true

  no-confirm:
    name: No Confirm
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Run clean-actions-runner
        id: clean_actions_runner
        uses: ./clean-actions-runner
        continue-on-error: true
        with:
          confirm: false
