---
name: 🧪 Test setup-crane

on:
  pull_request:
    branches:
      - main
    paths:
      - setup-crane/**

permissions: {}

jobs:
  test:
    name: Test (${{ matrix.version }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        version:
          - latest # default
          - v0.20.6 # specific version
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Run setup-crane
        id: setup_crane
        uses: ./setup-crane
        with:
          version: ${{ matrix.version }}

      - name: Test crane command
        id: test_crane_command
        run: |
          crane version
